# Generated by Django 4.2.29 on 2026-04-01 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('food', 'Food & Beverages'), ('beauty', 'Beauty & Personal Care'), ('home', 'Home & Kitchen'), ('books', 'Books & Education'), ('sports', 'Sports & Outdoors'), ('travel', 'Travel & Hotels'), ('software', 'Software & Apps'), ('other', 'Other')], default='other', max_length=50)),
                ('review_text', models.TextField()),
                ('result', models.CharField(choices=[('CG', 'Computer Generated'), ('OR', 'Original Review')], max_length=5)),
                ('confidence', models.FloatField(default=0.0)),
                ('detection_reasons', models.TextField(blank=True, default='')),
                ('is_flagged', models.BooleanField(default=False)),
                ('admin_override', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
